# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "467bd08fe63c860d98a1a6c97c6e6d91"
name = "daily-color-discounts"
handle = "daily-color-discounts"
application_url = "https://doe-one-hilton-finally.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "racreateapp.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_discounts_allocator_functions,write_products"

[auth]
redirect_urls = [
  "https://doe-one-hilton-finally.trycloudflare.com/auth/callback",
  "https://doe-one-hilton-finally.trycloudflare.com/auth/shopify/callback",
  "https://doe-one-hilton-finally.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
